[runbmc] Fix typo caused runbmc build error.
Miss a double quotation mark which caused following build error:
ERROR: ParseError at local.conf:6: unparsed line: 'USER_CLASSES ?= "buildstats'